name: Herobrine
main: net.theprogrammersworld.herobrine.Herobrine
version: 2.1.2
description: "Bring Herobrine to your Spigot-based Minecraft server!"
website: https://www.theprogrammersworld.net
api-version: 1.16
load: STARTUP
commands:
  test: